# Generated by Django 3.2.9 on 2021-11-26 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('patronymic', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('inn', models.CharField(max_length=50)),
                ('passport', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=50)),
                ('numbers', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('release_year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passengers_num', models.IntegerField(blank=True)),
                ('route_length', models.FloatField()),
                ('address_from', models.CharField(max_length=100)),
                ('address_to', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='taxi_orders.driver')),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='taxi_orders.machine'),
        ),
    ]
