# Generated by Django 3.2.9 on 2021-11-27 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['surname'], 'verbose_name': 'Водитель', 'verbose_name_plural': 'Водители'},
        ),
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['-release_year'], 'verbose_name': 'Машина', 'verbose_name_plural': 'Машины'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='driver',
            name='birthday',
            field=models.DateField(verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='inn',
            field=models.CharField(max_length=50, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='taxi_orders.machine', verbose_name='Машина'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='passport',
            field=models.CharField(max_length=50, verbose_name='Паспорт'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='patronymic',
            field=models.CharField(max_length=50, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='surname',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='brand',
            field=models.CharField(max_length=50, verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='color',
            field=models.CharField(max_length=50, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='level',
            field=models.CharField(max_length=50, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='numbers',
            field=models.CharField(max_length=50, verbose_name='Номера'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='release_year',
            field=models.DateField(db_index=True, verbose_name='Дата выпуска'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_from',
            field=models.CharField(max_length=100, verbose_name='Точка подачи'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_to',
            field=models.CharField(max_length=100, verbose_name='Точка назначения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='taxi_orders.driver', verbose_name='Водитель'),
        ),
        migrations.AlterField(
            model_name='order',
            name='passengers_num',
            field=models.IntegerField(blank=True, verbose_name='Количество пассажиров'),
        ),
        migrations.AlterField(
            model_name='order',
            name='route_length',
            field=models.FloatField(verbose_name='Длина пути (километры)'),
        ),
    ]
